
 _veh = createVehicle ['Land_HBarrierBig_F',[7108.62,7464.6,0.000352859],[],0,'NONE'];
 _veh setDir 261.761;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7110.74,7450.43,0],[],0,'NONE'];
 _veh setDir 262.775;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7105.96,7479.22,0],[],0,'NONE'];
 _veh setDir 261.246;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7082.41,7495.54,0],[],0,'NONE'];
 _veh setDir 351.075;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7105.21,7483.34,0],[],0,'NONE'];
 _veh setDir 261.246;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7065.76,7492.21,0],[],0,'NONE'];
 _veh setDir 349.141;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7086.94,7436.5,0],[],0,'NONE'];
 _veh setDir 172.53;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7113.07,7420.36,0.0231555],[],0,'NONE'];
 _veh setDir 261.824;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7103.74,7496.51,0],[],0,'NONE'];
 _veh setDir 82.8842;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7090.79,7497.07,0],[],0,'NONE'];
 _veh setDir 351.439;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7074.15,7493.99,0],[],0,'NONE'];
 _veh setDir 351.075;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7111.99,7443.6,0],[],0,'NONE'];
 _veh setDir 261.314;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_Sign_WarningMilitaryArea_F',[7048.7,7494.79,0],[],0,'NONE'];
 _veh setDir 79.7628;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7107.57,7470.75,0],[],0,'NONE'];
 _veh setDir 261.246;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7058.56,7490.68,0],[],0,'NONE'];
 _veh setDir 350.741;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7098.93,7498.96,0],[],0,'NONE'];
 _veh setDir 172.809;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7109.49,7457.96,0],[],0,'NONE'];
 _veh setDir 261.761;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7050.9,7489.19,0],[],0,'NONE'];
 _veh setDir 350.741;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7107.57,7431.3,0],[],0,'NONE'];
 _veh setDir 172.579;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7082.08,7435.6,0],[],0,'NONE'];
 _veh setDir 352.057;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7030.04,7479.42,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7031.61,7471.67,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7033.45,7463.81,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7035.1,7456.59,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7036.71,7449.82,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7038.39,7442.19,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7040.12,7434.44,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7041.77,7427.3,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7043.77,7487.93,0],[],0,'NONE'];
 _veh setDir 350.741;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7114.33,7412.35,0.0380824],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7111.66,7427,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7094.45,7428.83,0],[],0,'NONE'];
 _veh setDir 352.39;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7043.88,7417.15,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7099.51,7429.86,0],[],0,'NONE'];
 _veh setDir 353.107;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7029.76,7481.09,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7117.39,7396.22,0],[],0,'NONE'];
 _veh setDir 261.824;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7118.78,7388.08,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7115.99,7404.53,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7121.18,7372.81,0.0698473],[],0,'NONE'];
 _veh setDir 261.824;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7122.56,7364.67,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7119.78,7381.12,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7123.79,7356.98,0.0837123],[],0,'NONE'];
 _veh setDir 81.1674;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7126,7341.67,0],[],0,'NONE'];
 _veh setDir 262.575;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7127.27,7333.52,0.00106573],[],0,'NONE'];
 _veh setDir 81.1674;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7124.71,7350.01,0.0883775],[],0,'NONE'];
 _veh setDir 81.1674;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7128.33,7326.63,0],[],0,'NONE'];
 _veh setDir 81.1674;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7125.47,7321.03,0],[],0,'NONE'];
 _veh setDir 173.504;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7117.74,7319.86,0],[],0,'NONE'];
 _veh setDir 173.504;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7109.26,7318.68,0],[],0,'NONE'];
 _veh setDir 173.504;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7101.68,7317.73,0],[],0,'NONE'];
 _veh setDir 173.504;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7096.24,7316.55,0],[],0,'NONE'];
 _veh setDir 173.504;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7104.4,7489.41,0],[],0,'NONE'];
 _veh setDir 261.246;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7108.62,7439.8,0],[],0,'NONE'];
 _veh setDir 172.467;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7101.08,7438.55,0],[],0,'NONE'];
 _veh setDir 172.291;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7088.13,7428.02,0],[],0,'NONE'];
 _veh setDir 172.579;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7038.7,7487.13,0],[],0,'NONE'];
 _veh setDir 352.39;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7083.48,7427.11,0],[],0,'NONE'];
 _veh setDir 353.107;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7032.44,7485.76,0],[],0,'NONE'];
 _veh setDir 352.39;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7045.27,7409.13,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7046.83,7401.38,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7048.67,7393.52,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7050.33,7386.3,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7051.94,7379.54,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7053.62,7371.9,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7055.35,7364.15,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7057,7357.01,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7059.1,7346.87,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7060.55,7338.79,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7062.17,7332.02,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7063.85,7324.39,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7065.58,7316.64,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7074.71,7313.1,0],[],0,'NONE'];
 _veh setDir 352.588;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7088.58,7315.21,0],[],0,'NONE'];
 _veh setDir 350.411;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7081.29,7314.15,0],[],0,'NONE'];
 _veh setDir 354.639;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7055.21,7363.29,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7069.35,7312.63,0],[],0,'NONE'];
 _veh setDir 352.588;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7057.73,7353.18,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrierBig_F',[7043.24,7421.56,0],[],0,'NONE'];
 _veh setDir 80.4164;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrier_01_big_tower_green_F',[7093.42,7440.83,0],[],0,'NONE'];
 _veh setDir 350.644;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_HBarrier_01_tower_green_F',[7092.57,7491.64,0],[],0,'NONE'];
 _veh setDir 169.024;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_Cargo_Tower_V4_F',[7036.26,7479.49,0],[],0,'NONE'];
 _veh setDir 256.435;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_Cargo_Tower_V4_F',[7100.89,7465.23,0],[],0,'NONE'];
 _veh setDir 256.435;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_Cargo_Tower_V4_F',[7120.71,7328.53,0],[],0,'NONE'];
 _veh setDir 354.953;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_Cargo_Tower_V4_F',[7070.73,7322.54,0],[],0,'NONE'];
 _veh setDir 256.435;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_SM_01_shelter_wide_F',[7108.31,7380.6,0],[],0,'NONE'];
 _veh setDir 170.232;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 
 _veh = createVehicle ['Land_Airport_Tower_F',[7057.81,7397.74,0.282393],[],0,'NONE'];
 _veh setDir 76.0199;
 _veh setDamage 0;
 clearWeaponCargoGlobal _veh;clearMagazineCargoGlobal _veh;clearItemCargoGlobal _veh;_veh setVariable ["R3F_LOG_disabled", true,true]; 